# Generated by Django 3.2.4 on 2022-12-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0002_patient_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_year',
            field=models.DateField(max_length=10),
        ),
    ]
